In [4]:
import numpy as np
import pandas as pd

In [5]:
book = pd.read_csv("Data/Books.csv")
rating = pd.read_csv("Data/Ratings.csv")
users = pd.read_csv("Data/Users.csv")

C:\Users\rawat\AppData\Local\Temp\ipykernel_3696\2350495040.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  book = pd.read_csv("Data/Books.csv")

In [6]:
book.head(3)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...

In [14]:
rating.head(3)

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0

In [16]:
users.head(2)

   User-ID                   Location   Age
0        1         nyc, new york, usa   NaN
1        2  stockton, california, usa  18.0

## Checking for missing values

In [17]:
#book data
book.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [18]:
#user data
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

- Age is Missing in most of the data

In [19]:
#rating data
rating.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

## Duplicate data

In [22]:
data  = [book, users, rating]
for i in data:
    print(i.duplicated().sum())

0
0
0

### Popularity Based Recommendation System

In [33]:
ratings_with_name = rating.merge(book, on="ISBN")
ratings_with_name.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...

In [38]:
num_rating_df = ratings_with_name.groupby("Book-Title").count()["Book-Rating"].reset_index()
num_rating_df.rename(columns={"Book-Rating":"Num-Rating"}, inplace=True)

In [49]:
avg_rating_df = ratings_with_name.groupby("Book-Title").mean(numeric_only=True)["Book-Rating"].reset_index()
avg_rating_df.rename(columns = {"Book-Rating": "Avg-Rating"},inplace=True)

In [52]:
# Creating common df with both rating and num of data:
popular_df = num_rating_df.merge(avg_rating_df, on="Book-Title")
popular_df.head()

                                          Book-Title  Num-Rating  Avg-Rating
0   A Light in the Storm: The Civil War Diary of ...           4        2.25
1                              Always Have Popsicles           1        0.00
2               Apple Magic (The Collector's series)           1        0.00
3   Ask Lily (Young Women of Faith: Lily Series, ...           1        8.00
4   Beyond IBM: Leadership Marketing and Finance ...           1        0.00

In [55]:
# Books with rating more than 250 and popular
top_50_df = popular_df[popular_df["Num-Rating"]>=250].sort_values("Avg-Rating",ascending=False).reset_index().head(50)
top_50_df

,index,Book-Title,Num-Rating,Avg-Rating
0,80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
1,80422,Harry Potter and the Goblet of Fire (Book 4),387,5.824289
2,80441,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410
3,80426,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441
4,80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
5,191612,The Hobbit : The Enchanting Prelude to The Lor...,281,5.007117
6,187377,The Fellowship of the Ring (The Lord of the Ri...,368,4.948370
7,80445,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652
8,211384,"The Two Towers (The Lord of the Rings, Part 2)",260,4.880769
9,219741,To Kill a Mockingbird,510,4.700000
10,183573,The Da Vinci Code,898,4.642539
11,187880,The Five People You Meet in Heaven,430,4.551163
12,180556,The Catcher in the Rye,449,4.545657
13,196326,The Lovely Bones: A Novel,1295,4.468726
14,764,1984,284,4.454225
15,144165,Prodigal Summer: A Novel,253,4.450593
16,128670,Neverwhere,265,4.449057
17,206502,The Secret Life of Bees,774,4.447028
18,168719,Stupid White Men ...and Other Sorry Excuses fo...,283,4.356890
19,223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970
20,204387,The Red Tent (Bestselling Backlist),723,4.334716
21,191589,The Hitchhiker's Guide to the Galaxy,268,4.328358
22,129379,Nickel and Dimed: On (Not) Getting By in America,335,4.289552
23,93381,Into the Wild,252,4.273810
24,63867,Fahrenheit 451,409,4.264059
25,74750,Girl with a Pearl Earring,526,4.218631
26,136145,Outlander,283,4.173145
27,233370,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983
28,156102,Seabiscuit: An American Legend,275,4.098182
29,107962,Life of Pi,664,4.088855
30,176845,The Bean Trees,389,4.087404
31,2281,"A Child Called \It\"": One Child's Courage to S...",265,4.086792
32,8434,ANGELA'S ASHES,279,4.075269
33,76343,Good in Bed,490,4.055102
34,64931,Fast Food Nation: The Dark Side of the All-Ame...,321,4.037383
35,12700,American Gods,302,4.006623
36,161645,Skipping Christmas,322,4.006211
37,105777,Left Behind: A Novel of the Earth's Last Days ...,318,4.003145
38,189551,"The Golden Compass (His Dark Materials, Book 1)",336,4.000000
39,181679,The Color Purple,314,3.964968
40,160336,Silence of the Lambs,256,3.960938
41,8752,About a Boy,262,3.900763
42,158138,Seven Up (A Stephanie Plum Novel),278,3.888489
43,175097,The Alchemist: A Fable About Following Your Dream,266,3.875940
44,80069,Hard Eight : A Stephanie Plum Novel (A Stephan...,269,3.825279
45,170101,Suzanne's Diary for Nicholas,457,3.820569
46,111073,Lord of the Flies,259,3.818533
47,5664,A Prayer for Owen Meany,413,3.796610
48,212070,"The Vampire Lestat (Vampire Chronicles, Book II)",301,3.777409
49,233851,White Oleander : A Novel (Oprah's Book Club),356,3.772472

In [64]:
# Creating a data frame have all the information of the book with their no. of votes and average rating:
top_50_df = top_50_df.merge(book, on="Book-Title").drop_duplicates("Book-Title")[["Book-Title","Year-Of-Publication","Image-URL-M","Num-Rating","Avg-Rating"]]
top_50_df

,Book-Title,Year-Of-Publication,Image-URL-M,Num-Rating,Avg-Rating
0,Harry Potter and the Prisoner of Azkaban (Book 3),1999,http://images.amazon.com/images/P/0439136350.0...,428,5.852804
3,Harry Potter and the Goblet of Fire (Book 4),2000,http://images.amazon.com/images/P/0439139597.0...,387,5.824289
5,Harry Potter and the Sorcerer's Stone (Book 1),1998,http://images.amazon.com/images/P/0590353403.0...,278,5.737410
9,Harry Potter and the Order of the Phoenix (Boo...,2003,http://images.amazon.com/images/P/043935806X.0...,347,5.501441
13,Harry Potter and the Chamber of Secrets (Book 2),2000,http://images.amazon.com/images/P/0439064872.0...,556,5.183453
16,The Hobbit : The Enchanting Prelude to The Lor...,1986,http://images.amazon.com/images/P/0345339681.0...,281,5.007117
17,The Fellowship of the Ring (The Lord of the Ri...,1986,http://images.amazon.com/images/P/0345339703.0...,368,4.948370
26,Harry Potter and the Sorcerer's Stone (Harry P...,1999,http://images.amazon.com/images/P/059035342X.0...,575,4.895652
28,"The Two Towers (The Lord of the Rings, Part 2)",1986,http://images.amazon.com/images/P/0345339711.0...,260,4.880769
39,To Kill a Mockingbird,1988,http://images.amazon.com/images/P/0446310786.0...,510,4.700000
47,The Da Vinci Code,2003,http://images.amazon.com/images/P/0385504209.0...,898,4.642539
53,The Five People You Meet in Heaven,2003,http://images.amazon.com/images/P/0786868716.0...,430,4.551163
55,The Catcher in the Rye,1991,http://images.amazon.com/images/P/0316769487.0...,449,4.545657
62,The Lovely Bones: A Novel,2002,http://images.amazon.com/images/P/0316666343.0...,1295,4.468726
63,1984,1990,http://images.amazon.com/images/P/0451524934.0...,284,4.454225
72,Prodigal Summer: A Novel,2001,http://images.amazon.com/images/P/0060959037.0...,253,4.450593
73,Neverwhere,1998,http://images.amazon.com/images/P/0380789019.0...,265,4.449057
78,The Secret Life of Bees,2003,http://images.amazon.com/images/P/0142001740.0...,774,4.447028
84,Stupid White Men ...and Other Sorry Excuses fo...,2002,http://images.amazon.com/images/P/0060392452.0...,283,4.356890
85,"Tuesdays with Morrie: An Old Man, a Young Man,...",1997,http://images.amazon.com/images/P/0385484518.0...,493,4.354970
88,The Red Tent (Bestselling Backlist),1998,http://images.amazon.com/images/P/0312195516.0...,723,4.334716
89,The Hitchhiker's Guide to the Galaxy,1982,http://images.amazon.com/images/P/0671461494.0...,268,4.328358
98,Nickel and Dimed: On (Not) Getting By in America,2002,http://images.amazon.com/images/P/0805063897.0...,335,4.289552
100,Into the Wild,1997,http://images.amazon.com/images/P/0385486804.0...,252,4.273810
103,Fahrenheit 451,1994,http://images.amazon.com/images/P/3257208626.0...,409,4.264059
116,Girl with a Pearl Earring,2001,http://images.amazon.com/images/P/0452282152.0...,526,4.218631
117,Outlander,1996,http://images.amazon.com/images/P/0440222915.0...,283,4.173145
123,Where the Heart Is (Oprah's Book Club (Paperba...,1998,http://images.amazon.com/images/P/0446672211.0...,585,4.105983
124,Seabiscuit: An American Legend,2002,http://images.amazon.com/images/P/0449005615.0...,275,4.098182
126,Life of Pi,2002,http://images.amazon.com/images/P/0151008116.0...,664,4.088855
130,The Bean Trees,1989,http://images.amazon.com/images/P/0060915544.0...,389,4.087404
133,"A Child Called \It\"": One Child's Courage to S...",1995,http://images.amazon.com/images/P/1558743669.0...,265,4.086792
135,ANGELA'S ASHES,1996,http://images.amazon.com/images/P/0684874350.0...,279,4.075269
137,Good in Bed,2002,http://images.amazon.com/images/P/0743418174.0...,490,4.055102
139,Fast Food Nation: The Dark Side of the All-Ame...,2002,http://images.amazon.com/images/P/0060938455.0...,321,4.037383
140,American Gods,2002,http://images.amazon.com/images/P/0380789035.0...,302,4.006623
141,Skipping Christmas,2001,http://images.amazon.com/images/P/0385505833.0...,322,4.006211
147,Left Behind: A Novel of the Earth's Last Days ...,1996,http://images.amazon.com/images/P/0842329129.0...,318,4.003145
149,"The Golden Compass (His Dark Materials, Book 1)",2002,http://images.amazon.com/images/P/037582345X.0...,336,4.000000
157,The Color Purple,1985,http://images.amazon.com/images/P/0671617028.0...,314,3.964968
163,Silence of the Lambs,1991,http://images.amazon.com/images/P/0312924585.0...,256,3.960938
166,About a Boy,1999,http://images.amazon.com/images/P/1573227331.0...,262,3.900763
173,Seven Up (A Stephanie Plum Novel),2001,http://images.amazon.com/images/P/0312265840.0...,278,3.888489
175,The Alchemist: A Fable About Following Your Dream,1993,http://images.amazon.com/images/P/0062502174.0...,266,3.875940
177,Hard Eight : A Stephanie Plum Novel (A Stephan...,2003,http://images.amazon.com/images/P/0312983867.0...,269,3.825279
182,Suzanne's Diary for Nicholas,2001,http://images.amazon.com/images/P/0316969443.0...,457,3.820569
186,Lord of the Flies,1959,http://images.amazon.com/images/P/0399501487.0...,259,3.818533
192,A Prayer for Owen Meany,1990,http://images.amazon.com/images/P/0345361792.0...,413,3.796610
194,"The Vampire Lestat (Vampire Chronicles, Book II)",1986,http://images.amazon.com/images/P/0345313860.0...,301,3.777409
195,White Oleander : A Novel (Oprah's Book Club),2000,http://images.amazon.com/images/P/0316284955.0...,356,3.772472

### Collabrative base Recommendation System

In [65]:
ratings_with_name.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...

In [74]:
# find a User who has a minimum vote of 200 ( padhai likhaii users)
user_rating = ratings_with_name.groupby("User-ID").count().sort_values("Book-Rating",ascending=False)["ISBN"].reset_index()

In [79]:
padhe_likhe_user =user_rating[user_rating["ISBN"] > 200]["User-ID"].to_list()

In [83]:
# data of padhai likhai users
padhe_like_user_df = ratings_with_name[ratings_with_name["User-ID"].isin(padhe_likhe_user)]

In [92]:
# famous book read by padhai likhai users:
y = padhe_like_user_df.groupby("Book-Title").count()["Book-Rating"]>=50
famous_books = y[y].index

In [94]:
# final rating with user and books:
final_data = padhe_like_user_df[padhe_like_user_df["Book-Title"].isin(famous_books)]
final_data.shape

(58586, 10)

In [96]:
# Now making pivot table of user and books

pt = final_data.pivot_table(index="Book-Title",columns="User-ID",values="Book-Rating",fill_value=0)
pt.shape

(706, 810)

In [97]:
# Cosine similarities to find the similarities between the books.
from sklearn.metrics.pairwise import cosine_similarity
similarity_scores = cosine_similarity(pt)
similarity_scores.shape

(706, 706)

In [117]:
#Creating a function that recommends books
def recommend(book_name):
    #index fetching:
    index = np.where(pt.index==book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_scores[index])),key= lambda x:x[1], reverse=True)[1:9]
    for i in similar_items:
        print(pt.index[i[0]])

In [116]:
sorted(list(enumerate(similarity_scores[0])),key= lambda x:x[1], reverse=True)[1:9]

[(47, 0.2702651417103732),
 (545, 0.2639619371123497),
 (82, 0.23669374347400993),
 (634, 0.23299389358170394),
 (551, 0.2262639743141286),
 (181, 0.22222254415660225),
 (500, 0.21057743765309012),
 (344, 0.20675540390453995)]

In [109]:
np.where(pt.index=="A Bend in the Road")[0][0]

4

In [118]:
#Testing function
recommend("The Notebook")

A Walk to Remember
The Rescue
One Door Away from Heaven
Toxin
The Five People You Meet in Heaven
Nights in Rodanthe
Suzanne's Diary for Nicholas
Everything's Eventual : 14 Dark Tales

In [127]:
final_data["Image-URL-M"]

1150       http://images.amazon.com/images/P/002542730X.0...
1163       http://images.amazon.com/images/P/0060930535.0...
1165       http://images.amazon.com/images/P/0060934417.0...
1168       http://images.amazon.com/images/P/0061009059.0...
1174       http://images.amazon.com/images/P/006440188X.0...
                                 ...
1029196    http://images.amazon.com/images/P/1400031354.0...
1029197    http://images.amazon.com/images/P/1400031362.0...
1029270    http://images.amazon.com/images/P/1573229725.0...
1029309    http://images.amazon.com/images/P/1586210661.0...
1029310    http://images.amazon.com/images/P/1586212230.0...
Name: Image-URL-M, Length: 58586, dtype: object